=== rajesh-ss/cat01/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Company">
<xs:complexType>
<xs:sequence>
<xs:element name="Employee">
<xs:complexType>
<xs:sequence>
<xs:element name="Emp_name" type="xs:string"></xs:element>
<xs:element name="Emp_age" type="xs:ager"></xs:element>
<xs:element name="Emp_salary" type="xs:sal"></xs:element>
<xs:element name="Emp_emailid" type="string"></xs:element>
<xs:element name="Emp_phonenum" type="xs:integer"></xs:element>
<xs:element name="Emp_designation" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:attribute name="id" type="xs:ID" use="required"/>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="sal">
<xs:restriction base="xs:integer">
<xs:minInclusive value="50000"></xs:minInclusive>
<xs:maxInclusive value="200000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="ager">
<xs:restriction base="xs:integer">
<xs:minInclusive value="18"></xs:minInclusive>
<xs:maxInclusive value="100"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== rajesh-ss/cat01/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="emp.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emp.xsd">

	<Employee id='01'>
		<Emp_name>Rajesh</Emp_name>
		<Emp_age>23</Emp_age>
		<Emp_salary>51000</Emp_salary>
		<Emp_emailid>raju@gmail.com</Emp_emailid>
		<Emp_phonenum>8870078094</Emp_phonenum>
		<Emp_designation>trainee</Emp_designation>
	</Employee>
	<Employee id='02'>
		<Emp_name>Suresh</Emp_name>
		<Emp_age>52</Emp_age>
		<Emp_salary>120000</Emp_salary>
		<Emp_emailid>suresh@gmail.com</Emp_emailid>
		<Emp_phonenum>7469871234</Emp_phonenum>
		<Emp_designation>Associate</Emp_designation>
	</Employee>
	<Employee id='03'>
		<Emp_name>varun</Emp_name>
		<Emp_age>45</Emp_age>
		<Emp_salary>200000</Emp_salary>
		<Emp_emailid>varun@gmail.com</Emp_emailid>
		<Emp_phonenum>6974512385</Emp_phonenum>
		<Emp_designation>seniour associate</Emp_designation>
	</Employee>
	
</Company>
